# @package _global_

defaults:
  - /train
  - /_logging
  - override /dataset: rpdiff_point
  - override /model: df_point_cross
  - override /training: rpdiff_point_df_point_cross
  - _self_

dataset:
  data_dir: /home/odonca/workspace/rpad/data/rpdiff/data/rpdiff_preprocessed_mug-rack-multi
  misc_kwargs:
    rpdiff_type: multi_medrack
    rpdiff_descriptions_path: /home/odonca/workspace/rpad/data/rpdiff/data/descriptions
  num_demos: null

model:
  dit_arch: Rel3D_DiT_pcu_cross_xS

training:
  prediction_error_type: demo
  batch_size: 16