# @package _global_

defaults:
  - /train
  - /_logging
  - override /dataset: rpdiff_point
  - override /model: df_point_cross
  - override /training: rpdiff_point_df_point_cross
  - _self_

dataset:
  data_dir: /home/odonca/workspace/rpad/data/rpdiff/data/rpdiff_preprocessed_book-bookshelf_mod
  misc_kwargs:
    rpdiff_type: book_bookshelf
    rpdiff_descriptions_path: /home/odonca/workspace/rpad/data/rpdiff/data/descriptions

model:
  dit_arch: Rel3D_DiT_pcu_cross_xS
  x_relative: True

training:
  prediction_error_type: rpdiff_precision_wta
  batch_size: 16