# @package _global_

defaults:
  - /train
  - /_logging
  - override /dataset: ndf_point
  - override /model: df_point_cross
  - override /training: ndf_point_df_point_cross
  - _self_

dataset:
  num_demos: 10

model:
  dit_arch: Rel3D_DiT_pcu_cross_xS

training:
  prediction_error_type: distractor_min
  batch_size: 16