name: df_flow_cross

# Model settings
type: flow_cross
dit_arch: DiT_pcu_cross_xS
in_channels: 3
learn_sigma: True

x_encoder: mlp # Encoder current timestep x
y_encoder: dgcnn # Encoder for y object (e.g. anchor pcd)
x0_encoder: dgcnn # Encoder for x0 object (e.g. action pcd)

# Diffusion settings
diff_train_steps: 100
diff_inference_steps: 100
diff_noise_schedule: linear
diff_noise_scale: 1.0


