name: df_point

# Model settings
dit_arch: DiT_pcu_cross_xS
in_channels: 3
learn_sigma: True

x_encoder: mlp
pcd_encoder: dgcnn


# Diffusion settings
diff_train_steps: 100
diff_inference_steps: 100
diff_noise_schedule: squaredcos_cap_v2
diff_noise_scale: 0.25


