name: linear_regression

# Model settings
type: point # (flow, point) Type of model
size: xS # (xs, s, ...) Architecture of DiT
in_channels: 3 # Number of input channels
center_noise: False # Center noise for diffusion
rotary: False # Use rotary embedding for diffusion