name: ndf_point
data_dir: /home/triind/workspace/rpad/data/equivariant_pose_graph/data/mug_place_reduced
# data_dir: /home/triind/workspace/rpad/data/rpdiff/data/overfit_1r_1m_1d
type: ndf_point

###################################################
# General Dataset Parameters
###################################################
num_demos: 10 # Number of demonstrations to load
train_dataset_size: 1024 # Length of the train dataset
val_dataset_size: 64 # Length of the validation dataset

###################################################
# General Dataset Parameters
###################################################
center_type: anchor_center # [action_center, anchor_center, anchor_random, none], centers the point clouds w.r.t. the action, anchor, or no centering
sample_size: 512 # Number of points to downsample to
downsample_type: fps # [fps, random], downsampling method
pcd_scale_factor: 15.0 # Scale factor for the point clouds
action_transform_type: quat_uniform # Transformation type to apply to demonstrations
anchor_transform_type: random_flat_upright # Transformation type to apply to demonstrations
translation_variance: 0.0 # Translation variance of the demo transformation
rotation_variance: 180 # Rotation variance of the demo transformation

###################################################
# General Dataset Parameters
###################################################
distractor_anchor_pcds: 1 # Number of distractor anchor pcds to generate
distractor_transform_type: random_flat_upright # Transformation type to apply when generating distractor pcds
distractor_translation_variance: 0.5 # Translation variance of the distractor transformation
distractor_rotation_variance: 180 # Rotation variance of the distractor transformation

