name: point_overfit
# data_dir: ~/datasets/nrp/ProcCloth/single_cloth/demos
data_dir: /home/odonca/workspace/rpad/data/rpdiff/data/overfit_1r_1m_1d
type: point # 

# Dataset general options
num_demos: 1 # Number of demonstrations to load
train_dataset_size: 256 # Length of the train dataset
val_dataset_size: 4 # Length of the validation dataset

# Dataset pre-processing options
center_type: anchor # [action, anchor, none], centers the point clouds w.r.t. the action, anchor, or no centering
sample_size: 1024 # Number of points to downsample to
downsample_type: fps # [fps, random], downsampling method