name: rigid_point
# data_dir: ~/datasets/nrp/ProcCloth/single_cloth/demos
# data_dir: /home/triind/workspace/rpad/data/rpdiff/data/overfit_1r_1m_150d
data_dir: /home/triind/workspace/rpad/data/rpdiff/data/hard_k1_60r_50m_1000d
# data_dir: /home/triind/workspace/rpad/data/rpdiff/data/easy_utk4_10r_10m_250d
type: rigid_point

# Dataset general options
num_demos: null # Number of demonstrations to load
train_dataset_size: 2048 # Length of the train dataset
val_dataset_size: 16 # Length of the validation dataset

# Dataset pre-processing options
center_type: anchor_center # [action_center, anchor_center, anchor_random, none], centers the point clouds w.r.t. the action, anchor, or no centering
sample_size: 512 # Number of points to downsample to
downsample_type: fps # [fps, random], downsampling method
pcd_scale_factor: 15.0 # Scale factor for the point clouds
action_transform_type: identity # Transformation type to apply to demonstrations
anchor_transform_type: random_flat_upright # Transformation type to apply to demonstrations
translation_variance: 0.0 # Translation variance of the demo transformation
rotation_variance: 180 # Rotation variance of the demo transformation