name: rigid_flow
# data_dir: ~/datasets/nrp/ProcCloth/single_cloth/demos
data_dir: /home/odonca/workspace/rpad/data/rpdiff/data/overfit_1r_1m_1d
type: rigid_flow

# Dataset general options
num_demos: 1 # Number of demonstrations to load
train_dataset_size: 1024 # Length of the train dataset
val_dataset_size: 64 # Length of the validation dataset

# Dataset pre-processing options
center_type: anchor_center # [action_center, anchor_center, anchor_random, none], centers the point clouds w.r.t. the action, anchor, or no centering
sample_size: 512 # Number of points to downsample to
downsample_type: fps # [fps, random], downsampling method
pcd_scale_factor: 15.0 # Scale factor for the point clouds
action_transform_type: quat_uniform # Transformation type to apply to demonstrations
anchor_transform_type: quat_uniform # Transformation type to apply to demonstrations
translation_variance: 0.0 # Translation variance of the demo transformation
rotation_variance: 180 # Rotation variance of the demo transformation