# @package _global_
defaults:
    - /train@_here_
    - override /model: df_cross
    - override /dataset: proc_cloth
    - _self_

model:
    type: point

dataset:
    type: point
    scene: False
    world_frame: False
