name: Run Tests

on:
  workflow_call:
    inputs:
      install_string:
        required: True
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      ##############################################
      # Skip caching if using a local runner.
      - uses: actions/setup-python@v4
        if: ${{ !env.ACT }}
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: "pyproject.toml"
      - uses: actions/setup-python@v4
        if: ${{ env.ACT }}
        with:
          python-version: '3.10'
      ##############################################

      - name: Update pip and setuptools versions.
        run: pip install --upgrade pip==21 setuptools==65.5

      - name: Install torch dependencies because they are mean.
        run: pip install --extra-index-url https://download.pytorch.org/whl/cu118 torch==2.0.1+cu118 torchvision==0.15.2 torchaudio==2.0.2

      - name: Install torch geometric dependencies.
        run: pip install --find-links https://data.pyg.org/whl/torch-2.0.0+cu118.html pyg_lib==0.4.0 torch_scatter==2.1.2 torch_sparse==0.6.18 torch_cluster==1.6.3 torch_spline_conv==1.2.2


      - name: Install package
        run: pip install "${{ inputs.install_string }}"

      - name: Code Quality
        run: python -m black src/ tests/ --check

      - name: MyPy Typechecking
        run: python -m mypy src/ tests/

      # Run tests.
      - name: Test with pytest
        run: python -m pytest
